# Generated by Django 4.1.7 on 2023-03-27 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0006_alter_film_imdb_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='screenshot',
            name='name',
            field=models.CharField(default='Гавно, прикол не работает, хуйня, не ржака, саси член', max_length=100),
        ),
    ]
