# Generated by Django 4.1.7 on 2023-04-02 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0008_alter_screenshot_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='screenshot',
            name='name',
        ),
    ]
