# Generated by Django 4.1.7 on 2023-04-02 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0009_remove_screenshot_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='screenshot',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
