# Generated by Django 4.1.7 on 2023-04-04 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0010_screenshot_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='screenshot',
            old_name='name',
            new_name='file',
        ),
    ]
