# Generated by Django 4.1.7 on 2023-04-05 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0011_rename_name_screenshot_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='film',
            name='poster_name',
        ),
        migrations.AddField(
            model_name='film',
            name='poster_format',
            field=models.CharField(default='jpg', max_length=4),
            preserve_default=False,
        ),
    ]
