# Generated by Django 4.1.7 on 2023-04-12 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0013_genre_film_genre'),
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('age', models.IntegerField()),
                ('description', models.TextField()),
                ('photo_format', models.CharField(max_length=4)),
            ],
        ),
        migrations.RemoveField(
            model_name='film',
            name='genre',
        ),
        migrations.AddField(
            model_name='film',
            name='genres',
            field=models.ManyToManyField(db_table='FilmGenre', to='films.genre'),
        ),
        migrations.AddField(
            model_name='film',
            name='actors',
            field=models.ManyToManyField(db_table='FilmActor', to='films.actor'),
        ),
    ]
