# Generated by Django 4.1.7 on 2023-04-14 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0015_delete_actor_alter_film_actors'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genre',
            name='title',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
