# Generated by Django 4.1.7 on 2023-04-15 22:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0016_alter_genre_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='film',
            name='actors',
        ),
    ]
