# Generated by Django 4.1.7 on 2023-04-16 08:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('actors', '0002_alter_actor_age_alter_actor_description_and_more'),
        ('films', '0017_remove_film_actors'),
    ]

    operations = [
        migrations.CreateModel(
            name='FilmActor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='actors.actor')),
                ('film', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='films.film')),
            ],
        ),
        migrations.AddField(
            model_name='film',
            name='actors',
            field=models.ManyToManyField(through='films.FilmActor', to='actors.actor'),
        ),
    ]
