# Generated by Django 4.1.7 on 2023-04-16 12:24

from django.db import migrations, models
import films.validators


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0018_filmactor_film_actors'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='age_restriction',
            field=models.IntegerField(validators=[films.validators.validate_age_restriction]),
        ),
        migrations.AlterField(
            model_name='film',
            name='country',
            field=models.CharField(max_length=50, validators=[films.validators.validate_names]),
        ),
        migrations.AlterField(
            model_name='film',
            name='description',
            field=models.TextField(validators=[films.validators.validate_text]),
        ),
        migrations.AlterField(
            model_name='film',
            name='director',
            field=models.CharField(max_length=50, validators=[films.validators.validate_names]),
        ),
        migrations.AlterField(
            model_name='film',
            name='rating',
            field=models.DecimalField(decimal_places=2, max_digits=4, validators=[films.validators.validate_rating]),
        ),
        migrations.AlterField(
            model_name='film',
            name='studio',
            field=models.CharField(max_length=50, validators=[films.validators.validate_text]),
        ),
        migrations.AlterField(
            model_name='film',
            name='title',
            field=models.CharField(max_length=50, validators=[films.validators.validate_text]),
        ),
    ]
