# Generated by Django 4.1.7 on 2023-04-17 08:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('actors', '0004_alter_actor_name'),
        ('films', '0019_alter_film_age_restriction_alter_film_country_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filmactor',
            name='actor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='actors.actor'),
        ),
        migrations.AlterField(
            model_name='filmactor',
            name='film',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='films.film'),
        ),
    ]
