# Generated by Django 4.1.7 on 2023-05-20 08:08

from django.db import migrations, models
import films.validators


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0020_alter_filmactor_actor_alter_filmactor_film'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='film',
            name='age_restriction',
        ),
        migrations.AddField(
            model_name='film',
            name='content_rating',
            field=models.CharField(default='PG', max_length=25),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='film',
            name='rating',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=4, validators=[films.validators.validate_rating]),
        ),
    ]
