# Generated by Django 4.1.7 on 2023-05-21 15:10

from django.db import migrations, models

import films.validators


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0021_remove_film_age_restriction_film_content_rating_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='studio',
            field=models.CharField(max_length=100, validators=[films.validators.validate_text]),
        ),
    ]
