# Generated by Django 4.1.7 on 2023-05-25 21:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0022_alter_film_studio'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='film',
            unique_together={('title', 'release_date', 'director')},
        ),
    ]
