# Generated by Django 4.1.7 on 2023-05-31 08:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playlists', '0007_alter_playlist_films'),
        ('films', '0023_alter_film_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='FilmPlaylist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('film', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='films.film')),
                ('playlist', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='playlists.playlist')),
            ],
        ),
    ]
