# Generated by Django 4.1.7 on 2023-05-31 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0024_filmplaylist'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FilmPlaylist',
        ),
    ]
