# Generated by Django 4.1.7 on 2023-06-27 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0026_film_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
