# Generated by Django 4.1.7 on 2023-06-27 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0027_alter_film_slug'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='film',
            unique_together={('title', 'release_date')},
        ),
    ]
