# Generated by Django 4.1.7 on 2023-06-30 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0028_alter_film_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='genre',
            name='slug',
            field=models.SlugField(default=models.CharField(max_length=50, unique=True), unique=True),
        ),
    ]
