# Generated by Django 4.1.7 on 2023-07-02 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0030_alter_genre_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='film',
            name='imdb_rating',
        ),
    ]
