# Generated by Django 4.1.7 on 2023-04-18 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('films', '0020_alter_filmactor_actor_alter_filmactor_film'),
    ]

    operations = [
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, unique=True)),
                ('films', models.ManyToManyField(to='films.film')),
            ],
        ),
    ]
