# Generated by Django 4.1.7 on 2023-05-27 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playlists', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='user_id',
            field=models.IntegerField(default=10),
            preserve_default=False,
        ),
    ]
