# Generated by Django 4.1.7 on 2023-05-30 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playlists', '0003_alter_playlist_title_alter_playlist_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='is_default',
            field=models.BooleanField(default=False),
        ),
    ]
