# Generated by Django 4.1.7 on 2023-05-30 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playlists', '0004_playlist_is_default'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='user_type',
            field=models.CharField(choices=[('basic', 'basic'), ('admin', 'admin'), ('premium', 'premium')], default='basic', max_length=7),
            preserve_default=False,
        ),
    ]
