# Generated by Django 4.1.7 on 2023-05-31 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playlists', '0005_playlist_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlist',
            name='user_type',
            field=models.CharField(default='basic', max_length=7),
        ),
    ]
