# Generated by Django 4.1.7 on 2023-05-31 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0023_alter_film_unique_together'),
        ('playlists', '0006_alter_playlist_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlist',
            name='films',
            field=models.ManyToManyField(to='films.film'),
        ),
    ]
