# Generated by Django 4.1.7 on 2023-07-02 18:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('playlists', '0008_alter_playlist_films'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playlist',
            name='is_default',
        ),
        migrations.RemoveField(
            model_name='playlist',
            name='user_type',
        ),
        migrations.AlterField(
            model_name='playlist',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
