# Generated by Django 4.1.7 on 2023-07-02 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playlists', '0009_remove_playlist_is_default_remove_playlist_user_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='is_default',
            field=models.BooleanField(default=False),
        ),
    ]
