# Generated by Django 4.1.7 on 2023-07-02 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playlists', '0011_playlist_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlist',
            name='slug',
            field=models.SlugField(),
        ),
    ]
