# Generated by Django 4.1.7 on 2023-04-16 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0018_filmactor_film_actors'),
        ('actors', '0002_alter_actor_age_alter_actor_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='actor',
            name='films',
            field=models.ManyToManyField(through='films.FilmActor', to='films.film'),
        ),
    ]
