# Generated by Django 4.1.7 on 2023-04-16 12:24

from django.db import migrations, models
import films.validators


class Migration(migrations.Migration):

    dependencies = [
        ('actors', '0003_actor_films'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actor',
            name='name',
            field=models.CharField(max_length=50, unique=True, validators=[films.validators.validate_names]),
        ),
    ]
