# Generated by Django 4.1.7 on 2023-04-16 09:50

import actors.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actors', '0003_actor_films'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actor',
            name='name',
            field=models.CharField(max_length=50, unique=True, validators=[actors.validators.validate_name]),
        ),
    ]
