# Generated by Django 4.1.7 on 2023-05-20 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actors', '0005_remove_actor_age_actor_birth_date_actor_death_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actor',
            name='birth_date',
            field=models.DateField(null=True),
        ),
    ]
