# Generated by Django 4.1.7 on 2023-06-30 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actors', '0007_actor_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actor',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
